### ISSUE TITLE
Installing from secular partition

### ISSUE THREAD

**Issue by iluuu1994** [fasterthanlime/rock#817] opened 2014-09-18 18:56 UTC
I have Yosemite installed on a secular partition. I'm trying to install rock there.  
Apparently, the installation requires some assemblies embedded in Xcode. I get the following error message:

```
make

/Volumes/Macintosh HD/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
make: /Volumes/Macintosh: No such file or directory
make: *** [all] Error 1
```

It looks like the path doesn't get properly escaped. Any idea what I can do?

Btw, this compiler and the ooc language look amazing ✨

**Comment by fasterthanlime** [comment] 2015-07-09 19:40
Hey @iluuu1994, long overdue but.. can you still reproduce this issue? As far as I can tell, in rock's Makefile, make is only invoked via `$(MAKE)` which is the Right Way :tm: to do it, as far as I know!

`all-recursive` looks like it could be from Boehm GC. We've probably updated it since, so it might not occur anymore? I don't have that issue on OSX, but I don't have any funky partition layout either.

**Comment by iluuu1994** [comment] 2015-07-09 19:51
Well, I'm now back down to one partition so I can't test this. 
It's working now, so I'll let you decide if you want to close this issue or keep it ;)

**Comment by fasterthanlime** [comment] 2015-07-09 19:52
Well, it didn't seem exactly related to our own Makefile, so I'm gonna close it until someone encounters it again!

**Closed by fasterthanlime** 2015-07-09 19:52 UTC
Labels: Bug
